services:
  db-testing:
    image: postgres:12.22-bookworm
    restart: always
    user: postgres
    env_file: 
      - postgres-testing.env
    profiles:
      - dev

  backend-testing: 
    build:
      context: .
    env_file:
      - .env
      - postgres-testing.env
    profiles:
      - dev 
    ports:
      - 8080:80
    depends_on:
      - db-testing


  backend: 
    build:
      context: .
    env_file:
      - .env
      - postgres.env
    ports:
      - "3007:80"
    profiles:
      - prod

  db:
    image: postgres:12.22-bookworm
    restart: always
    user: postgres
    env_file: 
      - postgres.env
    volumes:
      - pg-prod:/var/lib/postgresql/data
    profiles:
      - prod

volumes: 
  pg-prod:
